export const volunteersActionTypes = {
  GET_VOLUNTEERS: 'GET_VOLUNTEERS',
  GET_VOLUNTEERS_SUCCESS: 'GET_VOLUNTEERS_SUCCESS',
  GET_VOLUNTEERS_ERROR: 'GET_VOLUNTEERS_ERROR',

  GET_ADDRESS_FILTERS: 'GET_ADDRESS_FILTERS',
  GET_ADDRESS_FILTERS_SUCCESS: 'GET_ADDRESS_FILTERS_SUCCESS',
  GET_ADDRESS_FILTERS_ERROR: 'GET_ADDRESS_FILTERS_ERROR',

  GET_CATEGORY_FILTERS: 'GET_CATEGORY_FILTERS',
  GET_CATEGORY_FILTERS_SUCCESS: 'GET_CATEGORY_FILTERS_SUCCESS',
  GET_CATEGORY_FILTERS_ERROR: 'GET_CATEGORY_FILTERS_ERROR',
}

export const volunteerStates = {
  volunteers: 'volunteers',
  sidoAddressFilters: 'sidoAddressFilters',
  sggAddressFilters: 'sggAddressFilters',
  categoryFilters: 'categoryFilters',
}